lib/friction_server_web/router.ex
defmodule FrictionServerWeb.Router do
  use FrictionServerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticated do
    plug FrictionServer.Pipelines.Auth
  end

  scope "/api/v1", FrictionServerWeb do
    pipe_through :api

    post "/users/signup", UserController, :create
    post "/users/login", UserController, :login

    post "/token", TokenController, :add_token

    pipe_through :authenticated
    get "/users", UserController, :show
    put "/users", UserController, :update
    delete "/users/:id", UserController, :delete

    get "/polls", PollController, :show_all
    get "/polls/latest", PollController, :show_latest
    get "/polls/:id", PollController, :show
    post "/polls", PollController, :create
    put "/polls/:id", PollController, :update
    delete "/polls/:id", PollController, :delete

    post "/votes", PollController, :add_vote
    put "/votes/:id", PollController, :update_vote
    get "/votes", PollController, :show_votes

    get "/polls/:id/messages", PollController, :get_messages
    get "/polls/:id/stats", PollController, :get_stats

    post "/messages/:id/claps", MessageController, :add_claps
    post "/messages/:id/dislikes", MessageController, :add_dislikes

    put "/messages/:message_id/claps/:clap_id", MessageController, :update_claps
    put "/messages/:message_id/dislikes/:dislike_id", MessageController, :update_dislikes

    post "/upload/image", UploadController, :upload
  end

  # Other scopes may use custom stacks.
  # scope "/api", FrictionServerWeb do
  #   pipe_through :api
  # end
end

lib/friction_server/accounts/user.ex
defmodule FrictionServer.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}

  @derive {Poison.Encoder, except: [:__meta__, :password, :password_hash, :votes, :tokens]}

  schema "users" do
    field :email, :string
    field :image_url, :string
    field :name, :string
    field :password, :string, virtual: true
    field :password_hash, :string
    has_many :votes, FrictionServer.Clashes.Vote, foreign_key: :user_id
    has_many :tokens, FrictionServer.Notifications.Token, foreign_key: :user_id

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email, :image_url])
    |> validate_required([:name, :email])
    |> validate_email
  end

  def registration_changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email, :image_url, :password])
    |> validate_required([:name, :email, :password])
    |> validate_changeset
  end

  def image_changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:image_url])
  end

  defp validate_changeset(struct) do
    struct
    |> validate_email
    |> validate_password
  end

  defp validate_email(struct) do
    struct
    |> validate_length(:email, min: 5, max: 255)
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email)
  end

  defp validate_password(struct) do
    struct
    |> validate_length(:password, min: 6)
      #    |> validate_format(:password, ~r/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).*/, [message: "Must include at least one lowercase letter, one uppercase letter, and one digit"])
    |> generate_password_hash
  end

  defp generate_password_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: password}} ->
        put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(password))
      _ ->
        changeset
    end
  end
end

lib/friction_server_web/controllers/user_controller.ex
defmodule FrictionServerWeb.UserController do
  use FrictionServerWeb, :controller

  alias FrictionServer.Accounts
  alias FrictionServer.Accounts.User

  def create(conn, params) do
    case Accounts.create_user(params) do
      {:ok, user} ->
        {:ok, jwt, _full_claims} = FrictionServer.Authentication.Guardian.encode_and_sign(user, %{}, permissions: %{user: []})
        conn
        |> send_resp(200, Poison.encode!(%{token: jwt, user: user}))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def login(conn, %{"email" => email, "password" => password}) do
    case Accounts.get_authenticated_user(email, password) do
      {:ok, user} ->
        {:ok, jwt, _full_claims} = FrictionServer.Authentication.Guardian.encode_and_sign(user, %{}, permissions: %{user: []})
        conn
        |> send_resp(200, Poison.encode!(%{token: jwt, user: user}))
      {:error, reason} ->
        conn
        |> send_resp(401, Poison.encode!(%{message: "Invalid email or password"}))
    end
  end

  def show(conn, _params) do
    user = FrictionServer.Authentication.Guardian.Plug.current_resource(conn)

    conn
    |> send_resp(200, Poison.encode!(user))
  end

  def update(conn, params) do
    user = FrictionServer.Authentication.Guardian.Plug.current_resource(conn)

    case Accounts.update_user(user, params) do
      {:ok, user} ->
        conn
        |> send_resp(200, Poison.encode!(user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> send_resp(200, Poison.encode!(%{message: "Success"}))
  end
end

lib/friction_server_web/views/user_view.ex
defmodule FrictionServerWeb.UserView do
  use FrictionServerWeb, :view
end

lib/friction_server_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/friction_server_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :image_url, class: "control-label" %>
    <%= text_input f, :image_url, class: "form-control" %>
    <%= error_tag f, :image_url %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= text_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :password_hash, class: "control-label" %>
    <%= text_input f, :password_hash, class: "form-control" %>
    <%= error_tag f, :password_hash %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/friction_server_web/templates/user/index.html.eex
<h2>Listing Users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Image url</th>
      <th>Password</th>
      <th>Password hash</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.image_url %></td>
      <td><%= user.password %></td>
      <td><%= user.password_hash %></td>

      <td class="text-right">
        <span><%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: user_path(@conn, :new) %></span>

lib/friction_server_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/friction_server_web/templates/user/show.html.eex
<h2>Show User</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Image url:</strong>
    <%= @user.image_url %>
  </li>

  <li>
    <strong>Password:</strong>
    <%= @user.password %>
  </li>

  <li>
    <strong>Password hash:</strong>
    <%= @user.password_hash %>
  </li>

</ul>

<span><%= link "Edit", to: user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: user_path(@conn, :index) %></span>